GET http://localhost:3001/api/notes

###
GET http://localhost:3001/api/notes/1

###
GET http://localhost:3001/api/notes/5

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "Learn Node.js",
  "important": true
}

###
POST http://localhost:5000/api/persons
Content-Type: application/json

{
    "name": "ertyui",
    "number": "5789654123"
}

###
POST http://localhost:5000/api/persons
Content-Type: application/json

{
    "name": "tyhgbnj",
    "number": "9874563210"
}